List<String> dummyIndustriesData = [
  'Automobiles & Components',
  'Industry',
  'Banks & Insurance',
  'Consumer Durables & Apparel',
  'Consumer Services',
  'Energy & Utilities',
  'Media',
  'Retailing',
  'Software & Services',
  'Telecommunication Services',
  'Transportation',
  'Health Care Equipment & Services',
  'Materials',
  'Pharmaceuticals, Biotechnology & Life Sciences',
  'Real Estate',
  'Consumer Staples',
  'Diversified Financials & Financial Services',
  'Food & Beverage & Tobacco',
  'Capital Goods',
  'Consumer Discretionary',
  'Commercial & Professional Services',
  'Independent Power and Renewable Electricity Producers',
];
